### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by AnonymousFreeS2** [game-lover/game-lover.github.io#1]
I saw account 2020vis13079846 and was very angry I used his programs for a whole year and it turned out that they were stolen. I hate him. I have information about the rune language (as his last tweets he renamed rune to U) that Ivan wants to publish I proved that he wants to copy another big project You are interested?

**Comment by game-lover** [comment]
¯\\\_(ツ)\_/¯ I know about entynetproject and enty8080 much more than you

**Comment by game-lover** [comment]
What do you want?

**Comment by AnonymousFreeS2** [comment]
Ivan want to stole Odin Programming Language, U language very similar to it. That’s all I want to say.
